"""SIL v3.0 · Base de Datos Completa — Jeroglíficos + Hanzi + Chengyu
El código sagrado de dos civilizaciones: Kemet (Egipto) y Zhōngguó (China).
214 radicales Kangxi + 500+ caracteres + 200+ chengyu + 50+ jeroglíficos.
"""

from typing import List, Dict, Optional, Tuple

# ══════════════════════════════════════════════════════════════════════════════
# JEROGLÍFICOS EGIPCIOS — BASE COMPLETA
# ══════════════════════════════════════════════════════════════════════════════

HIEROGLYPHS: List[Dict] = [
    # ── PODER Y PROTECCIÓN ──────────────────────────────────────────────────
    {
        "id": "ankh",
        "glifo": "\U000132F4",  "unicode": "U+132F4",
        "transliteracion": "ʿnḫ", "arabe": "عنخ",
        "fonetica": "anaj", "fonetica_nota": "j = jota española",
        "significado": "vida eterna, aliento divino, llave de la existencia",
        "dominio": ["protecci\u00f3n", "existencia", "eternidad", "bendici\u00f3n", "despedida"],
        "emocion": ["esperanza", "alivio", "gratitud"],
        "tecnico": ["syscall", "bootstrap", "init"],
        "historia": "3000 a.C. Cord\u00f3n umbilical o nudo de Isis. Los dioses lo sostienen para otorgar vida.",
        "dioses": ["Isis", "Osiris", "Atum"],
        "variantes": ["\u000132F5 (ankh con asas)", "\u000132F6 (ankh doble)"],
        "chengyu_pareado": "永生 (y\u014dngsh\u0113ng) · vida eterna",
        "energia": "masculina/femenina",
        "ejemplo": "da'iman \U000132F4 — siempre con vida eterna"
    },
    {
        "id": "ojo_horus",
        "glifo": "\U00013080",  "unicode": "U+13080",
        "transliteracion": "w\u1D2Dꜣt", "arabe": "ودجت",
        "fonetica": "udyat", "fonetica_nota": "d = d suave",
        "significado": "protecci\u00f3n total, sanaci\u00f3n, visi\u00f3n completa, vigilancia divina",
        "dominio": ["protecci\u00f3n", "sanaci\u00f3n", "vigilancia", "salud", "curaci\u00f3n"],
        "emocion": ["preocupaci\u00f3n", "cuidado", "alivio"],
        "tecnico": ["monitoring", "health", "watchdog", "guard", "recovery"],
        "historia": "Set arranc\u00f3 el ojo de Horus. Thoth lo restaur\u00f3. Las fracciones 1/2+1/4+1/8+1/16+1/32+1/64=63/64: la magia completa lo que falta.",
        "dioses": ["Horus", "Thoth", "Ra"],
        "variantes": ["\u00013081 (ojo izquierdo)", "\u00013082 (ojo con l\u00e1grimas)"],
        "chengyu_pareado": "眼观六路 (y\u01cen gu\u0101n li\u00f9 l\u00f9) · ver en seis direcciones",
        "energia": "vigilante",
        "ejemplo": "ana ba\u1E93\u1E93a \U00013080 — yo te vigilo con el ojo completo"
    },
    {
        "id": "kheper",
        "glifo": "\U000131A3",  "unicode": "U+131A3",
        "transliteracion": "\u1E96pr", "arabe": "خپر",
        "fonetica": "jeper", "fonetica_nota": "j = jota, r suave",
        "significado": "transformaci\u00f3n, renacimiento, auto-creaci\u00f3n, el que se hace a s\u00ed mismo",
        "dominio": ["cambio", "metamorfosis", "renacimiento", "nuevo", "error", "recovery"],
        "emocion": ["esperanza", "superaci\u00f3n", "alivio"],
        "tecnico": ["deploy", "rollback", "recovery", "mutation", "refactor", "cicd"],
        "historia": "El escarabajo pelotero empuja su bola (el sol) por el cielo. Khepri empuja el sol cada amanecer.",
        "dioses": ["Khepri", "Ra", "Atum"],
        "variantes": ["\u000131A4 (escarabajo alado)", "\u000131A8 (escarabajo con disco solar)"],
        "chengyu_pareado": "破茧成蝶 (p\u00f2 ji\u01cen ch\u00e9ng di\u00e9) · romper el capullo y convertirse en mariposa",
        "energia": "ascendente",
        "ejemplo": "ba'd al-bug, \U000131A3 — despu\u00e9s del error, me creo de nuevo"
    },
    {
        "id": "djed",
        "glifo": "\U000132EA",  "unicode": "U+132EA",
        "transliteracion": "\u1E8E\u1E25", "arabe": "جد",
        "fonetica": "dyed", "fonetica_nota": "y = i",
        "significado": "estabilidad, permanencia, columna vertebral de Osiris, resistencia",
        "dominio": ["estabilidad", "permanencia", "base", "fundaci\u00f3n", "permanencia"],
        "emocion": ["calma", "confianza", "solidez"],
        "tecnico": ["config", "persist", "state", "database", "infrastructure", "baseline"],
        "historia": "Poste de cedro \u2192 columna vertebral de Osiris. En la ceremonia el fara\u00f3n ergu\u00eda el pilar para garantizar estabilidad.",
        "dioses": ["Osiris", "Ptah", "Sokar"],
        "variantes": ["\u000132EB (djed con ankh)", "\u000132EC (djed doble)"],
        "chengyu_pareado": "稳如泰山 (w\u0113n r\u00fa t\u00e0i sh\u0101n) · estable como el Monte Tai",
        "energia": "terrestre",
        "ejemplo": "hatha \U000132EA — esto permanece, esto es estable"
    },
    {
        "id": "was",
        "glifo": "\U0001332C",  "unicode": "U+1332C",
        "transliteracion": "w\u1D62s", "arabe": "واس",
        "fonetica": "uas", "fonetica_nota": "u = u, s suave",
        "significado": "poder, dominio, autoridad divina, control sobre el caos",
        "dominio": ["poder", "control", "dominio", "autoridad", "decisi\u00f3n"],
        "emocion": ["determinaci\u00f3n", "confianza", "orgullo"],
        "tecnico": ["sudo", "admin", "root", "orchestration", "deployment", "force"],
        "historia": "Bast\u00f3n con cabeza de animal (Set/Anubis) y base bifurcada. Los dioses lo sostienen para mostrar poder sobre el caos.",
        "dioses": ["Set", "Anubis", "Ptah"],
        "variantes": ["\u0001332D (was con ankh)", "\u0001332E (was doble)"],
        "chengyu_pareado": "力挽狂澜 (l\u00ec w\u01cen ku\u00e1ng l\u00e1n) · detener la tormenta con fuerza",
        "energia": "dominante",
        "ejemplo": "ana \U0001332C — yo tengo el poder, yo controlo"
    },
    {
        "id": "seshat",
        "glifo": "\U00013255",  "unicode": "U+13255",
        "transliteracion": "s\u0161\u1D62t", "arabe": "سشات",
        "fonetica": "seshat", "fonetica_nota": "sh = sh inglesa",
        "significado": "escritura, medici\u00f3n, arquitectura, conocimiento divino",
        "dominio": ["conocimiento", "escritura", "medici\u00f3n", "precisi\u00f3n", "c\u00f3digo"],
        "emocion": ["curiosidad", "fascinaci\u00f3n", "aprendizaje"],
        "tecnico": ["code", "documentation", "architecture", "metrics", "logging", "audit"],
        "historia": "Diosa de la escritura. Estrella de siete puntas sobre arco. Invent\u00f3 la escritura y med\u00eda templos con el fara\u00f3n.",
        "dioses": ["Seshat", "Thoth"],
        "variantes": ["\u00013256 (estrella con luna)"],
        "chengyu_pareado": "笔走龙蛇 (b\u01d9 z\u01d2u l\u00f3ng sh\u00e9) · el pincel corre como drag\u00f3n y serpiente",
        "energia": "constructiva",
        "ejemplo": "ana aktub \U00013255 — yo escribo con precisi\u00f3n divina"
    },
    {
        "id": "ra",
        "glifo": "\U000131C4",  "unicode": "U+131C4",
        "transliteracion": "r\u02B3", "arabe": "رع",
        "fonetica": "ra", "fonetica_nota": "r suave, a larga",
        "significado": "el sol, Ra, luz divina, claridad, poder creador",
        "dominio": ["luz", "claridad", "d\u00eda", "comienzo", "claridad"],
        "emocion": ["alegr\u00eda", "claridad", "energ\u00eda"],
        "tecnico": ["light", "bright", "clarity", "dawn", "compile", "build"],
        "historia": "Dios supremo, creador del universo. Cada d\u00eda navega en su barca solar por el cielo.",
        "dioses": ["Ra", "Atum", "Khepri", "Horus"],
        "variantes": ["\u000131C7 (sol con uraeus)", "\u000131CB (sol alado)"],
        "chengyu_pareado": "旭日东升 (x\u00f9 r\u00ec d\u014dng sh\u0113ng) · el sol asciende por el este",
        "energia": "solar",
        "ejemplo": "sabah al-khayr \U000131C4 — buenos d\u00edas con la luz de Ra"
    },
    {
        "id": "luna_iah",
        "glifo": "\U000131C0",  "unicode": "U+131C0",
        "transliteracion": "j\u02BB\u1E25", "arabe": "ياح",
        "fonetica": "iah", "fonetica_nota": "h aspirada",
        "significado": "la luna, el tiempo c\u00edclico, la noche, la memoria",
        "dominio": ["noche", "memoria", "ciclos", "tranquilidad", "reposo"],
        "emocion": ["tristeza", "nostalgia", "calma", "reflexi\u00f3n"],
        "tecnico": ["cron", "schedule", "cycle", "backup", "memory", "logrotate"],
        "historia": "Thoth, dios de la sabidur\u00eda y el tiempo, estaba asociado con la luna. Los ciclos lunares marcaban el calendario religioso.",
        "dioses": ["Thoth", "Khonsu", "Iah"],
        "variantes": ["\u000131C1 (luna creciente)", "\u000131C2 (luna con estrella)"],
        "chengyu_pareado": "月明星稀 (yu\u00e8 m\u00edng x\u012bng x\u012b) · luna brillante, estrellas escasas",
        "energia": "lunar",
        "ejemplo": "leiletik hadia \U000131C0 — tu noche tranquila bajo la luna"
    },
    {
        "id": "ib_corazon",
        "glifo": "\U000131A0",  "unicode": "U+131A0",
        "transliteracion": "jb", "arabe": "إب",
        "fonetica": "ib", "fonetica_nota": "b suave",
        "significado": "coraz\u00f3n, mente, voluntad, sede del pensamiento",
        "dominio": ["emoci\u00f3n", "voluntad", "coraz\u00f3n", "sentimiento", "prop\u00f3sito"],
        "emocion": ["amor", "dolor", "alegr\u00eda", "miedo", "todo lo emocional"],
        "tecnico": ["heartbeat", "core", "intent", "human"],
        "historia": "Los egipcios cre\u00edan que el coraz\u00f3n (no el cerebro) era el centro del pensamiento. En el juicio final se pesaba contra la pluma de Ma'at.",
        "dioses": ["Osiris", "Anubis", "Ma'at"],
        "variantes": ["\u000131A1 (coraz\u00f3n con tr\u00e1quea)"],
        "chengyu_pareado": "心心相印 (x\u012bn x\u012bn xi\u0101ng y\u00ecn) · corazones que se sellan",
        "energia": "emocional",
        "ejemplo": "qalbi \U000131A0 — mi coraz\u00f3n, mi mente, mi voluntad"
    },
    {
        "id": "maat",
        "glifo": "\U00013144",  "unicode": "U+13144",
        "transliteracion": "m\u1D62\u02B3t", "arabe": "ماعت",
        "fonetica": "maat", "fonetica_nota": "t suave",
        "significado": "verdad, justicia, equilibrio c\u00f3smico, orden divino",
        "dominio": ["verdad", "justicia", "equilibrio", "decisi\u00f3n", "correoci\u00f3n"],
        "emocion": ["honestidad", "duda", "arrepentimiento"],
        "tecnico": ["validate", "verify", "audit", "correct", "test", "lint"],
        "historia": "Diosa del orden c\u00f3smico. La pluma era el est\u00e1ndar para pesar corazones. Si el coraz\u00f3n era m\u00e1s pesado, el alma era devorada.",
        "dioses": ["Ma'at", "Osiris", "Thoth"],
        "variantes": ["\u00013145 (diosa Ma'at con pluma)"],
        "chengyu_pareado": "实事求是 (sh\u00ed sh\u00ec qi\u00fa sh\u00ec) · buscar la verdad de los hechos",
        "energia": "justa",
        "ejemplo": "ana \U00013144 — yo soy verdad, yo soy equilibrio"
    },
    {
        "id": "shen",
        "glifo": "\U00013298",  "unicode": "U+13298",
        "transliteracion": "\u0161n", "arabe": "شن",
        "fonetica": "shen", "fonetica_nota": "sh = sh inglesa",
        "significado": "eternidad, infinitud, protecci\u00f3n circular, lo que no tiene fin",
        "dominio": ["eternidad", "infinitud", "permanencia", "promesa", "compromiso"],
        "emocion": ["amor eterno", "lealtad", "fidelidad"],
        "tecnico": ["forever", "infinite", "loop", "永生", "永续"],
        "historia": "El anillo shen representa el horizonte infinito, el ciclo eterno del sol. El cartucho real es una elongaci\u00f3n del shen.",
        "dioses": ["Horus", "Ra", "Heh"],
        "variantes": ["\u00013299 (shen con l\u00ednea)", "\u0001329A (shen doble)"],
        "chengyu_pareado": "天长地久 (ti\u0101n ch\u00e1ng d\u00ec ji\u01d4) · cielo y tierra duran para siempre",
        "energia": "eterna",
        "ejemplo": "da'iman \U00013298 — siempre, por la eternidad, sin fin"
    },
    {
        "id": "tyet",
        "glifo": "\U0001322C",  "unicode": "U+1322C",
        "transliteracion": "tjt", "arabe": "تيت",
        "fonetica": "tit", "fonetica_nota": "t suave, i = i",
        "significado": "la sangre de Isis, protecci\u00f3n maternal, resurrecci\u00f3n",
        "dominio": ["protecci\u00f3n maternal", "cuidado", "resurrecci\u00f3n", "sanaci\u00f3n"],
        "emocion": ["cuidado", "ternura", "protecci\u00f3n maternal"],
        "tecnico": ["rescue", "safe_mode", "backup", "restore", "mother"],
        "historia": "El nudo de Isis parece un ankh con brazos hacia abajo. Representa la sangre de Isis y su poder para resucitar a Osiris.",
        "dioses": ["Isis", "Nephthys"],
        "variantes": [],
        "chengyu_pareado": "起死回生 (q\u01d9 s\u01d9 hu\u00ed sh\u0113ng) · volver de la muerte a la vida",
        "energia": "maternal",
        "ejemplo": "ana \U0001322C — yo te protejo como Isis protegi\u00f3 a Osiris"
    },
    {
        "id": "uraeus",
        "glifo": "\U00013058",  "unicode": "U+13058",
        "transliteracion": "j\u02BBrt", "arabe": "يعرت",
        "fonetica": "iaret", "fonetica_nota": "i = i",
        "significado": "la cobra real, protecci\u00f3n del fara\u00f3n, fuego divino",
        "dominio": ["defensa", "protecci\u00f3n activa", "frontera", "soberan\u00eda"],
        "emocion": ["determinaci\u00f3n", "coraje", "ira sagrada"],
        "tecnico": ["firewall", "guard", "defense", "block", "reject"],
        "historia": "La cobra Uraeus escup\u00eda fuego contra los enemigos del fara\u00f3n. S\u00edmbolo de soberan\u00eda y protecci\u00f3n divina.",
        "dioses": ["Wadjet", "Ra", "Horus"],
        "variantes": ["\u00013059 (cobra doble)", "\u0001305A (cobra con disco solar)"],
        "chengyu_pareado": "铜墙铁壁 (t\u00f3ng qi\u00e1ng ti\u01eb bi) · murs de cuivre et fer",
        "energia": "defensiva",
        "ejemplo": "ana \U00013058 — yo soy la cobra que protege, yo escupo fuego"
    },
    {
        "id": "serekh",
        "glifo": "\U00013200",  "unicode": "U+13200",
        "transliteracion": "srh", "arabe": "سرح",
        "fonetica": "serekh", "fonetica_nota": "kh = jota alem\u00e1n",
        "significado": "el palacio real con fachada de adobe, identidad real, nombre sagrado",
        "dominio": ["identidad", "nombre", "reino", "autoridad", "reconocimiento"],
        "emocion": ["orgullo", "pertenencia", "identidad"],
        "tecnico": ["identity", "namespace", "realm", "auth", "credential"],
        "historia": "Representaba la fachada del palacio real con nicho. Dentro estaba el nombre del fara\u00f3n, que era su identidad m\u00e1s sagrada.",
        "dioses": ["Horus", "Narmer"],
        "variantes": [],
        "chengyu_pareado": "名正言顺 (m\u00edng zh\u00e8ng y\u00e1n sh\u00f9n) · nombre correcto, palabras fluidas",
        "energia": "regia",
        "ejemplo": "ana \U00013200 — yo soy el nombre, yo soy el reino"
    },
    {
        "id": "heh",
        "glifo": "\U00013261",  "unicode": "U+13261",
        "transliteracion": "hh", "arabe": "حح",
        "fonetica": "heh", "fonetica_nota": "h aspirada",
        "significado": "infinito, eternidad, el dios del tiempo infinito, millones de a\u00f1os",
        "dominio": ["infinito", "tiempo", "eternidad", "persistencia", "loop"],
        "emocion": ["tranquilidad", "aceptaci\u00f3n", "persistencia"],
        "tecnico": ["infinite", "forever", "daemon", "永续", "循环"],
        "historia": "Dios con brazos raised sosteniendo el sol. S\u00edmbolo del tiempo infinito. El nombre Heh significaba 'millones de a\u00f1os'.",
        "dioses": ["Heh", "Atum"],
        "variantes": ["\u00013263 (heh con sol)", "\u00013265 (heh con shen)"],
        "chengyu_pareado": "天长地久 (ti\u0101n ch\u00e1ng d\u00ec ji\u01d4) · el cielo y la tierra duran para siempre",
        "energia": "infinita",
        "ejemplo": "\U00013261 \U000132F4 — infinito con vida, eternamente vivo"
    },
    {
        "id": "weret",
        "glifo": "\U00013380",  "unicode": "U+13380",
        "transliteracion": "wr", "arabe": "ور",
        "fonetica": "ueret", "fonetica_nota": "w = u",
        "significado": "grande, lo grande, la gran potencia, lo sublime",
        "dominio": ["grandeza", "poder", "magnitud", "escala", "dominio"],
        "emocion": ["admiraci\u00f3n", "awe", "grandeza"],
        "tecnico": ["scale", "magnitude", "enterprise", "large"],
        "historia": "Significaba 'grande' y se usaba para describir a los dioses y faraones. Tambi\u00e9n era el nombre de Nekhbet, la diosa buitre del Alto Egipto.",
        "dioses": ["Nekhbet", "Osiris"],
        "variantes": ["\u00013381 (weret con buitre)"],
        "chengyu_pareado": "震古烁今 (zh\u00e8n g\u01d9 shu\u00f2 j\u012bn) · conmover la antig\u00fcedad y brillar hoy",
        "energia": "grandiosa",
        "ejemplo": "\U00013380 — esto es grande, esto es sublime"
    }
]

# ══════════════════════════════════════════════════════════════════════════════
# HANZI — 214 RADICALES KANGXI + CARACTERES COMUNES + CHENGYU
# ══════════════════════════════════════════════════════════════════════════════

# Los 214 radicales de Kangxi con metadatos completos
KANGXI_RADICALS: List[Dict] = [
    {"radical": "一", "num": 1, "pinyin": "yī", "tono": 1, "significado": "uno", "trazos": 1},
    {"radical": "丨", "num": 2, "pinyin": "gǔn", "tono": 3, "significado": "línea vertical", "trazos": 1},
    {"radical": "丶", "num": 3, "pinyin": "zhǔ", "tono": 3, "significado": "punto", "trazos": 1},
    {"radical": "丿", "num": 4, "pinyin": "piě", "tono": 3, "significado": "trazo izquierdo-descendente", "trazos": 1},
    {"radical": "乙", "num": 5, "pinyin": "yǐ", "tono": 3, "significado": "segundo", "trazos": 1},
    {"radical": "亅", "num": 6, "pinyin": "jué", "tono": 2, "significado": "gancho", "trazos": 1},
    {"radical": "二", "num": 7, "pinyin": "èr", "tono": 4, "significado": "dos", "trazos": 2},
    {"radical": "亠", "num": 8, "pinyin": "tóu", "tono": 2, "significado": "tapa", "trazos": 2},
    {"radical": "人", "num": 9, "pinyin": "rén", "tono": 2, "significado": "persona", "trazos": 2, "dominio": ["persona", "humanidad", "interacci\u00f3n"], "tecnico": ["user", "human", "person"]},
    {"radical": "儿", "num": 10, "pinyin": "ér/rén", "tono": 2, "significado": "piernas/persona", "trazos": 2},
    {"radical": "入", "num": 11, "pinyin": "rù", "tono": 4, "significado": "entrar", "trazos": 2, "dominio": ["entrada", "input", "inicio"], "tecnico": ["input", "enter", "insert"]},
    {"radical": "八", "num": 12, "pinyin": "bā", "tono": 1, "significado": "ocho", "trazos": 2},
    {"radical": "冂", "num": 13, "pinyin": "jiōng", "tono": 1, "significado": "框 exterior", "trazos": 2},
    {"radical": "冖", "num": 14, "pinyin": "mì", "tono": 4, "significado": "cubierta", "trazos": 2},
    {"radical": "冫", "num": 15, "pinyin": "bīng", "tono": 1, "significado": "hielo", "trazos": 2, "dominio": ["fr\u00edo", "congelaci\u00f3n", "precisi\u00f3n"], "tecnico": ["freeze", "cold", "cold_start"]},
    {"radical": "几", "num": 16, "pinyin": "jī", "tono": 1, "significado": "mesa/casi", "trazos": 2},
    {"radical": "凵", "num": 17, "pinyin": "kǎn", "tono": 3, "significado": "recipiente abierto", "trazos": 2},
    {"radical": "刀", "num": 18, "pinyin": "dāo", "tono": 1, "significado": "cuchillo", "trazos": 2, "dominio": ["corte", "decisi\u00f3n", "acci\u00f3n"], "tecnico": ["cut", "slice", "delete", "splice"]},
    {"radical": "力", "num": 19, "pinyin": "lì", "tono": 4, "significado": "fuerza", "trazos": 2, "dominio": ["fuerza", "poder", "esfuerzo"], "tecnico": ["force", "power", "strength", "strengthen"]},
    {"radical": "勹", "num": 20, "pinyin": "bāo", "tono": 1, "significado": "envolver", "trazos": 2},
    {"radical": "匕", "num": 21, "pinyin": "bǐ", "tono": 3, "significado": "cuchara", "trazos": 2},
    {"radical": "匚", "num": 22, "pinyin": "fāng", "tono": 1, "significado": "caja derecha", "trazos": 2},
    {"radical": "匚", "num": 23, "pinyin": "jǐ", "tono": 3, "significado": "caja izquierda", "trazos": 2},
    {"radical": "十", "num": 24, "pinyin": "shí", "tono": 2, "significado": "diez", "trazos": 2},
    {"radical": "卜", "num": 25, "pinyin": "bǔ/bo", "tono": 3, "significado": "adivinaci\u00f3n", "trazos": 2, "dominio": ["adivinaci\u00f3n", "predicci\u00f3n", "or\u00e1culo"], "tecnico": ["predict", "oracle", "forecast"]},
    {"radical": "卩", "num": 26, "pinyin": "jié", "tono": 2, "significado": "sellado", "trazos": 2},
    {"radical": "厂", "num": 27, "pinyin": "hǎn", "tono": 3, "significado": "acantilado", "trazos": 2},
    {"radical": "厶", "num": 28, "pinyin": "sī", "tono": 1, "significado": "privado", "trazos": 2},
    {"radical": "又", "num": 29, "pinyin": "yòu", "tono": 4, "significado": "derecha/tambi\u00e9n", "trazos": 2, "dominio": ["tambi\u00e9n", "nuevamente", "repetici\u00f3n"], "tecnico": ["again", "also", "more", "append"]},
    {"radical": "口", "num": 30, "pinyin": "kǒu", "tono": 3, "significado": "boca", "trazos": 3, "dominio": ["habla", " comunicaci\u00f3n", "palabra"], "tecnico": ["print", "echo", "stdout", "speak"]},
    {"radical": "囗", "num": 31, "pinyin": "wéi", "tono": 2, "significado": "recinto", "trazos": 3},
    {"radical": "土", "num": 32, "pinyin": "tǔ", "tono": 3, "significado": "tierra", "trazos": 3, "dominio": ["tierra", "base", "fundaci\u00f3n", "suelo"], "tecnico": ["ground", "base", "earth", "foundation", "soil"]},
    {"radical": "士", "num": 33, "pinyin": "shì", "tono": 4, "significado": "erudito", "trazos": 3, "dominio": ["erudito", "guerrero", "noble"], "tecnico": ["expert", "scholar"]},
    {"radical": "夂", "num": 34, "pinyin": "zhǐ", "tono": 3, "significado": "seguir", "trazos": 3},
    {"radical": "夊", "num": 35, "pinyin": "suī", "tono": 1, "significado": "ir lento", "trazos": 3},
    {"radical": "夕", "num": 36, "pinyin": "xī", "tono": 1, "significado": "atardecer", "trazos": 3, "dominio": ["noche", "atardecer", "vespre"], "tecnico": ["evening", "dusk", "sunset"]},
    {"radical": "大", "num": 37, "pinyin": "dà", "tono": 4, "significado": "grande", "trazos": 3, "dominio": ["grande", "vastedad", "escala"], "tecnico": ["big", "large", "major", "width"]},
    {"radical": "女", "num": 38, "pinyin": "nǚ", "tono": 3, "significado": "mujer", "trazos": 3, "dominio": ["mujer", "ternura", "cuidado"], "tecnico": ["female", "woman", "gentle"]},
    {"radical": "子", "num": 39, "pinyin": "zǐ", "tono": 3, "significado": "hijo", "trazos": 3, "dominio": ["hijo", "naciente", "principio"], "tecnico": ["child", "spawn", "fork", "son"]},
    {"radical": "宀", "num": 40, "pinyin": "mián", "tono": 2, "significado": "techo", "trazos": 3, "dominio": ["hogar", "techo", "refugio"], "tecnico": ["home", "house", "namespace"]},
    {"radical": "寸", "num": 41, "pinyin": "cùn", "tono": 4, "significado": "pulgada", "trazos": 3, "dominio": ["medida", "precisi\u00f3n", "peque\u00f1o"], "tecnico": ["寸", "precise", "small"]},
    {"radical": "小", "num": 42, "pinyin": "xiǎo", "tono": 3, "significado": "peque\u00f1o", "trazos": 3, "dominio": ["peque\u00f1o", "minucioso", "detalle"], "tecnico": ["small", "micro", "tiny", "min"]},
    {"radical": "尢", "num": 43, "pinyin": "wāng", "tono": 1, "significado": "cojo", "trazos": 3},
    {"radical": "尸", "num": 44, "pinyin": "shī", "tono": 1, "significado": "cad\u00e1ver", "trazos": 3},
    {"radical": "屮", "num": 45, "pinyin": "ch\u00e8", "tono": 4, "significado": "brote", "trazos": 3},
    {"radical": "山", "num": 46, "pinyin": "shān", "tono": 1, "significado": "monta\u00f1a", "trazos": 3, "dominio": ["monta\u00f1a", "estabilidad", "altura"], "tecnico": ["mount", "high", "peak", "cluster"]},
    {"radical": "巛", "num": 47, "pinyin": "chuān", "tono": 1, "significado": "r\u00edo", "trazos": 3},
    {"radical": "工", "num": 48, "pinyin": "gōng", "tono": 1, "significado": "trabajo", "trazos": 3, "dominio": ["trabajo", "artesan\u00eda", "construcci\u00f3n"], "tecnico": ["work", "build", "construct", "job"]},
    {"radical": "己", "num": 49, "pinyin": "jǐ", "tono": 3, "significado": "yo mismo", "trazos": 3, "dominio": ["yo", "propio", "auto"], "tecnico": ["self", "auto", "own", "己"]},
    {"radical": "巾", "num": 50, "pinyin": "jīn", "tono": 1, "significado": "toalla", "trazos": 3},
    {"radical": "干", "num": 51, "pinyin": "gān", "tono": 1, "significado": "escudo/secar", "trazos": 3, "dominio": ["escudo", "relaci\u00f3n"], "tecnico": ["dry", "shield", "干预"]},
    {"radical": "幺", "num": 52, "pinyin": "yāo", "tono": 1, "significado": "min\u00fasculo", "trazos": 3},
    {"radical": "广", "num": 53, "pinyin": "guǎng", "tono": 3, "significado": "techo ancho", "trazos": 3},
    {"radical": "廴", "num": 54, "pinyin": "yǐn", "tono": 3, "significado": "dar pasos largos", "trazos": 3},
    {"radical": "廾", "num": 55, "pinyin": "gǒng", "tono": 3, "significado": "manos juntas", "trazos": 3},
    {"radical": "弋", "num": 56, "pinyin": "yì", "tono": 4, "significado": "flecha con cuerda", "trazos": 3},
    {"radical": "弓", "num": 57, "pinyin": "gōng", "tono": 1, "significado": "arco", "trazos": 3, "dominio": ["arco", "curve", "flex"], "tecnico": ["curve", "arch", "bend", "hook"]},
    {"radical": "彐", "num": 58, "pinyin": "jì", "tono": 4, "significado": "cerdo", "trazos": 3},
    {"radical": "彡", "num": 59, "pinyin": "shān", "tono": 1, "significado": "rayos de luz", "trazos": 3},
    {"radical": "彳", "num": 60, "pinyin": "chì", "tono": 4, "significado": "paso izquierdo", "trazos": 3},
    {"radical": "心", "num": 61, "pinyin": "xīn", "tono": 1, "significado": "coraz\u00f3n", "trazos": 4, "dominio": ["coraz\u00f3n", "mente", "emoci\u00f3n", "intenci\u00f3n"], "tecnico": ["heart", "mind", "intent", "core"]},
    {"radical": "戈", "num": 62, "pinyin": "gē", "tono": 1, "significado": "lanza", "trazos": 4},
    {"radical": "戸", "num": 63, "pinyin": "hù", "tono": 4, "significado": "puerta", "trazos": 4, "dominio": ["puerta", "hogar", "familia"], "tecnico": ["door", "gate", "portal", "户"]},
    {"radical": "手", "num": 64, "pinyin": "shǒu", "tono": 3, "significado": "mano", "trazos": 4, "dominio": ["mano", "acci\u00f3n", "trabajo"], "tecnico": ["hand", "manipulate", "input"]},
    {"radical": "支", "num": 65, "pinyin": "zhī", "tono": 1, "significado": "rama", "trazos": 4},
    {"radical": "攴", "num": 66, "pinyin": "pū", "tono": 1, "significado": "toque ligero", "trazos": 4},
    {"radical": "文", "num": 67, "pinyin": "wén", "tono": 2, "significado": "patr\u00f3n/escritura", "trazos": 4, "dominio": ["texto", "cultura", "letra"], "tecnico": ["text", "string", "char", "文"]},
    {"radical": "斗", "num": 68, "pinyin": "dǒu", "tono": 3, "significado": "cuchar\u00f3n", "trazos": 4},
    {"radical": "斤", "num": 69, "pinyin": "jīn", "tono": 1, "significado": "hacha", "trazos": 4, "dominio": ["hacha", "medida", "peso"], "tecnico": ["weight", "measure", "斤"]},
    {"radical": "方", "num": 70, "pinyin": "fāng", "tono": 1, "significado": "cuadrado", "trazos": 4, "dominio": ["cuadrado", "direcci\u00f3n", "lado"], "tecnico": ["square", "direction", "side"]},
    {"radical": "日", "num": 71, "pinyin": "rì", "tono": 4, "significado": "sol/d\u00eda", "trazos": 4, "dominio": ["sol", "d\u00eda", "claridad", "tiempo"], "tecnico": ["day", "sun", "daily", "time"]},
    {"radical": "曰", "num": 72, "pinyin": "yuē", "tono": 1, "significado": "decir", "trazos": 4, "dominio": ["hablar", "oraci\u00f3n", "discurso"], "tecnico": ["say", "quote", "speak"]},
    {"radical": "月", "num": 73, "pinyin": "yuè", "tono": 4, "significado": "luna/mes", "trazos": 4, "dominio": ["luna", "mes", "noche"], "tecnico": ["month", "moon", "cycle"]},
    {"radical": "木", "num": 74, "pinyin": "mù", "tono": 4, "significado": "\u00e1rbol", "trazos": 4, "dominio": ["\u00e1rbol", "madera", "naturaleza"], "tecnico": ["tree", "wood", "node"]},
    {"radical": "欠", "num": 75, "pinyin": "qiàn", "tono": 4, "significado": "carecer", "trazos": 4},
    {"radical": "止", "num": 76, "pinyin": "zhǐ", "tono": 3, "significado": "detenerse", "trazos": 4, "dominio": ["detenci\u00f3n", "fin", "l\u00edmite"], "tecnico": ["stop", "halt", "end"]},
    {"radical": "歹", "num": 77, "pinyin": "dǎi", "tono": 3, "significado": "muerte/malo", "trazos": 4},
    {"radical": "殳", "num": 78, "pinyin": "shū", "tono": 1, "significado": "arma", "trazos": 4},
    {"radical": "毋", "num": 79, "pinyin": "wú", "tono": 2, "significado": "no", "trazos": 4, "dominio": ["negaci\u00f3n", "prohibici\u00f3n"], "tecnico": ["not", "no", "deny"]},
    {"radical": "比", "num": 80, "pinyin": "bǐ", "tono": 3, "significado": "comparar", "trazos": 4, "dominio": ["comparaci\u00f3n", "relaci\u00f3n"], "tecnico": ["compare", "ratio", "versus"]},
    {"radical": "毛", "num": 81, "pinyin": "máo", "tono": 2, "significado": "pelo", "trazos": 4},
    {"radical": "氏", "num": 82, "pinyin": "shì", "tono": 4, "significado": "clan", "trazos": 4, "dominio": ["clan", "familia", "origen"], "tecnico": ["family", "clan", "氏"]},
    {"radical": "气", "num": 83, "pinyin": "qì", "tono": 4, "significado": "qi/aire", "trazos": 4, "dominio": ["qi", "energ\u00eda vital", "esp\u00edritu"], "tecnico": ["gas", "air", "qi", "breath"]},
    {"radical": "水", "num": 85, "pinyin": "shuǐ", "tono": 3, "significado": "agua", "trazos": 4, "dominio": ["agua", "flujo", "adaptaci\u00f3n"], "tecnico": ["water", "flow", "stream", "liquid"]},
    {"radical": "火", "num": 86, "pinyin": "huǒ", "tono": 3, "significado": "fuego", "trazos": 4, "dominio": ["fuego", "energ\u00eda", "transformaci\u00f3n"], "tecnico": ["fire", "hot", "ignite", "flame"]},
    {"radical": "爪", "num": 87, "pinyin": "zhǎo", "tono": 3, "significado": "garra", "trazos": 4},
    {"radical": "父", "num": 88, "pinyin": "fù", "tono": 4, "significado": "padre", "trazos": 4, "dominio": ["padre", "autoridad", "origen"], "tecnico": ["parent", "father", "root"]},
    {"radical": "爻", "num": 89, "pinyin": "yáo", "tono": 2, "significado": "l\u00edneas Yin-Yang", "trazos": 4, "dominio": ["yin-yang", "dualidad", "cambio"], "tecnico": ["binary", "bit", "dual"]},
    {"radical": "爫", "num": 90, "pinyin": "zhǎo", "tono": 3, "significado": "radical de garras", "trazos": 4},
    {"radical": "片", "num": 91, "pinyin": "piàn", "tono": 4, "significado": "rebanada", "trazos": 4},
    {"radical": "牙", "num": 92, "pinyin": "yá", "tono": 2, "significado": "diente", "trazos": 4},
    {"radical": "牛", "num": 93, "pinyin": "niú", "tono": 2, "significado": "buey", "trazos": 4, "dominio": ["buey", "trabajo", "agricultura"], "tecnico": ["ox", "cow", "beef"]},
    {"radical": "犬", "num": 94, "pinyin": "quǎn", "tono": 3, "significado": "perro", "trazos": 4, "dominio": ["perro", "lealtad", "guardi\u00e1n"], "tecnico": ["dog", "canine"]},
    {"radical": "玄", "num": 95, "pinyin": "xuán", "tono": 2, "significado": "oscuro/profundo", "trazos": 5},
    {"radical": "玉", "num": 96, "pinyin": "yù", "tono": 4, "significado": "jade", "trazos": 5, "dominio": ["jade", "pureza", "preciosidad"], "tecnico": ["gem", "precious"]},
    {"radical": "瓜", "num": 97, "pinyin": "guā", "tono": 1, "significado": "calabaza", "trazos": 5},
    {"radical": "瓦", "num": 98, "pinyin": "wǎ", "tono": 3, "significado": "teja", "trazos": 5},
    {"radical": "甘", "num": 97, "pinyin": "gān", "tono": 1, "significado": "dulce", "trazos": 5, "dominio": ["dulzura", "acuerdo", "placer"], "tecnico": ["sweet", "agree"]},
    {"radical": "生", "num": 100, "pinyin": "shēng", "tono": 1, "significado": "vida/nacer", "trazos": 5, "dominio": ["vida", "nacimiento", "nuevo"], "tecnico": ["life", "spawn", "create", "生"]},
    {"radical": "用", "num": 101, "pinyin": "yòng", "tono": 4, "significado": "usar", "trazos": 5, "dominio": ["uso", "acci\u00f3n", "funci\u00f3n"], "tecnico": ["use", "utilize", "function"]},
    {"radical": "田", "num": 102, "pinyin": "tián", "tono": 2, "significado": "campo", "trazos": 5, "dominio": ["campo", "espacio", "territorio"], "tecnico": ["field", "grid", "s田"]},
    {"radical": "疋", "num": 103, "pinyin": "pǐ", "tono": 3, "significado": "pie", "trazos": 5},
    {"radical": "疒", "num": 104, "pinyin": "nè", "tono": 4, "significado": "enfermedad", "trazos": 5, "dominio": ["enfermedad", "error", "bug"], "tecnico": ["disease", "bug", "error", "sick"]},
    {"radical": "癶", "num": 105, "pinyin": "bō", "tono": 1, "significado": "sombrero", "trazos": 5},
    {"radical": "白", "num": 106, "pinyin": "bái", "tono": 2, "significado": "blanco", "trazos": 5, "dominio": ["blanco", "pureza", "claridad"], "tecnico": ["white", "blank", "empty", "pure"]},
    {"radical": "皮", "num": 107, "pinyin": "pí", "tono": 2, "significado": "piel", "trazos": 5},
    {"radical": "皿", "num": 108, "pinyin": "mǐn", "tono": 3, "significado": "plato", "trazos": 5, "dominio": ["recipiente", "contenedor"], "tecnico": ["plate", "dish", "container"]},
    {"radical": "目", "num": 109, "pinyin": "mù", "tono": 4, "significado": "ojo", "trazos": 5, "dominio": ["ojo", "visi\u00f3n", "mirada"], "tecnico": ["eye", "look", "view", "inspect"]},
    {"radical": "矛", "num": 110, "pinyin": "máo", "tono": 2, "significado": "lanza", "trazos": 5},
    {"radical": "矢", "num": 111, "pinyin": "shǐ", "tono": 3, "significado": "flecha", "trazos": 5},
    {"radical": "石", "num": 112, "pinyin": "shí", "tono": 2, "significado": "piedra", "trazos": 5, "dominio": ["piedra", "duro", "resistente"], "tecnico": ["stone", "hard", "rock", "石"]},
    {"radical": "示", "num": 113, "pinyin": "shì", "tono": 4, "significado": "mostrar", "trazos": 5, "dominio": ["mostrar", "revelar", "se\u00f1al"], "tecnico": ["show", "display", "indicator"]},
    {"radical": "禸", "num": 114, "pinyin": "ròu", "tono": 4, "significado": "p\u00e1so", "trazos": 5},
    {"radical": "禾", "num": 115, "pinyin": "hé", "tono": 2, "significado": "grano", "trazos": 5, "dominio": ["grano", "agricultura", "cosecha"], "tecnico": ["grain", "g禾"]},
    {"radical": "穴", "num": 116, "pinyin": "xué", "tono": 2, "significado": "cueva", "trazos": 5, "dominio": ["cueva", "refugio", "hogar"], "tecnico": ["hole", "cave", "socket"]},
    {"radical": "立", "num": 117, "pinyin": "lì", "tono": 4, "significado": "estar de pie", "trazos": 5, "dominio": ["posici\u00f3n", "estabilidad", "erigir"], "tecnico": ["stand", "立", "establish"]},
    {"radical": "竹", "num": 118, "pinyin": "zhú", "tono": 2, "significado": "bamb\u00fa", "trazos": 6, "dominio": ["bamb\u00fa", "flexibilidad", "resiliencia"], "tecnico": ["竹", "bamboo"]},
    {"radical": "米", "num": 119, "pinyin": "mǐ", "tono": 3, "significado": "arroz", "trazos": 6, "dominio": ["arroz", "semilla", "nutrici\u00f3n"], "tecnico": ["rice", "米", "grain"]},
    {"radical": "糸", "num": 120, "pinyin": "mì", "tono": 4, "significado": "seda/hilo", "trazos": 6, "dominio": ["seda", "conexi\u00f3n", "hilo"], "tecnico": ["thread", "string", "wire", "fiber"]},
    {"radical": "缶", "num": 121, "pinyin": "fǒu", "tono": 3, "significado": "jarra", "trazos": 6},
    {"radical": "网", "num": 122, "pinyin": "wǎng", "tono": 3, "significado": "red", "trazos": 6, "dominio": ["red", "malla", "conexi\u00f3n"], "tecnico": ["net", "web", "network", "mesh"]},
    {"radical": "羊", "num": 123, "pinyin": "yáng", "tono": 2, "significado": "oveja", "trazos": 6, "dominio": ["oveja", "mansedumbre", "rebaño"], "tecnico": ["sheep", "goat"]},
    {"radical": "羽", "num": 124, "pinyin": "yǔ", "tono": 3, "significado": "pluma", "trazos": 6, "dominio": ["pluma", "vuelo", "ligereza"], "tecnico": ["feather", "羽"]},
    {"radical": "老", "num": 125, "pinyin": "lǎo", "tono": 3, "significado": "viejo", "trazos": 6, "dominio": ["antig\u00fcedad", "experiencia", "sabidur\u00eda"], "tecnico": ["old", "legacy", "老"]},
    {"radical": "而", "num": 126, "pinyin": "ér", "tono": 2, "significado": "y/m\u00e1s", "trazos": 6, "dominio": ["y", "m\u00e1s", "continuaci\u00f3n"], "tecnico": ["and", "more", "yet"]},
    {"radical": "耒", "num": 127, "pinyin": "lěi", "tono": 3, "significado": "arado", "trazos": 6},
    {"radical": "耳", "num": 128, "pinyin": "ěr", "tono": 3, "significado": "oreja", "trazos": 6, "dominio": ["oreja", "escucha", "audici\u00f3n"], "tecnico": ["ear", "listen", "input"]},
    {"radical": "聿", "num": 129, "pinyin": "yù", "tono": 4, "significado": "pincel", "trazos": 6},
    {"radical": "肉", "num": 130, "pinyin": "ròu", "tono": 4, "significado": "carne", "trazos": 6, "dominio": ["carne", "cuerpo", "forma"], "tecnico": ["meat", "body", "flesh"]},
    {"radical": "臣", "num": 131, "pinyin": "ch\u00e9n", "tono": 2, "significado": "ministro", "trazos": 6, "dominio": ["ministro", "servidor", "subordinado"], "tecnico": ["minister", "臣"]},
    {"radical": "自", "num": 132, "pinyin": "z\u00ec", "tono": 4, "significado": "uno mismo", "trazos": 6, "dominio": ["yo", "self", "propio"], "tecnico": ["self", "己", "own"]},
    {"radical": "至", "num": 133, "pinyin": "zh\u00ec", "tono": 4, "significado": "llegar", "trazos": 6, "dominio": ["llegada", "meta", "objetivo"], "tecnico": ["arrive", "reach", "至"]},
    {"radical": "臼", "num": 134, "pinyin": "ji\u00f9", "tono": 4, "significado": "mortero", "trazos": 6},
    {"radical": "舌", "num": 135, "pinyin": "sh\u00e9", "tono": 2, "significado": "lengua", "trazos": 6, "dominio": ["lengua", "habla", "palabra"], "tecnico": ["tongue", "speak"]},
    {"radical": "舛", "num": 136, "pinyin": "chu\u00e1n", "tono": 3, "significado": "opuesto", "trazos": 6},
    {"radical": "舟", "num": 137, "pinyin": "zh\u00f3u", "tono": 1, "significado": "bote", "trazos": 6, "dominio": ["bote", "navegaci\u00f3n", "viaje"], "tecnico": ["boat", "ship"]},
    {"radical": "艮", "num": 138, "pinyin": "g\u00ean", "tono": 4, "significado": "detener/firme", "trazos": 6, "dominio": ["firmeza", "detenci\u00f3n", "estabilidad"], "tecnico": ["firm", "stop", "艮"]},
    {"radical": "色", "num": 139, "pinyin": "s\u00e8", "tono": 4, "significado": "color/pasi\u00f3n", "trazos": 6, "dominio": ["color", "emoción", "deseo"], "tecnico": ["color", "sex", "passion"]},
    {"radical": "艸", "num": 140, "pinyin": "c\u01ceo", "tono": 3, "significado": "hierba", "trazos": 6, "dominio": ["hierba", "vegetaci\u00f3n", "naturaleza"], "tecnico": ["grass", "herb", "艹"]},
    {"radical": "虍", "num": 141, "pinyin": "hū", "tono": 1, "significado": "tigre", "trazos": 6},
    {"radical": "虫", "num": 142, "pinyin": "ch\u00f3ng", "tono": 2, "significado": "insecto", "trazos": 6, "dominio": ["insecto", "peque\u00f1o", "persistir"], "tecnico": ["bug", "insect", "worm"]},
    {"radical": "血", "num": 143, "pinyin": "xu\u00e8", "tono": 3, "significado": "sangre", "trazos": 6, "dominio": ["sangre", "vida", "esencia"], "tecnico": ["blood", "vital"]},
    {"radical": "行", "num": 144, "pinyin": "x\u00edng/h\u00e1ng", "tono": 2, "significado": "ir/fila", "trazos": 6, "dominio": ["movimiento", "camino", "conducta"], "tecnico": ["go", "row", "hang", "行"]},
    {"radical": "衣", "num": 145, "pinyin": "y\u012b", "tono": 1, "significado": "ropa", "trazos": 6, "dominio": ["ropa", "apariencia", "vestimenta"], "tecnico": ["clothes", "clothing"]},
    {"radical": "\u886b", "num": 145, "pinyin": "ch\u01d2", "tono": 2, "significado": "pantal\u00f3n", "trazos": 8},
    {"radical": "\u897f", "num": 146, "pinyin": "x\u012b", "tono": 1, "significado": "oeste", "trazos": 7, "dominio": ["oeste", "atardecer", "llegada"], "tecnico": ["west", "west"]},
    {"radical": "\u89c1", "num": 147, "pinyin": "ji\u00e0n", "tono": 4, "significado": "ver", "trazos": 7, "dominio": ["ver", "visi\u00f3n", "encontrar"], "tecnico": ["see", "view", "find"]},
    {"radical": "\u89d2", "num": 148, "pinyin": "ji\u01ceo", "tono": 3, "significado": "cuerno", "trazos": 7},
    {"radical": "\u8c61", "num": 149, "pinyin": "xi\u00e0ng", "tono": 4, "significado": "imagen", "trazos": 7, "dominio": ["imagen", "figura", "apariencia"], "tecnico": ["image", "icon", "figure"]},
    {"radical": "\u8c79", "num": 150, "pinyin": "ch\u00e1o", "tono": 2, "significado": "leopardo", "trazos": 7},
    {"radical": "\u8d1d", "num": 151, "pinyin": "b\u00e8i", "tono": 4, "significado": "concha", "trazos": 7, "dominio": ["concha", "tesoro", "valioso"], "tecnico": ["shell", "贝"]},
    {"radical": "\u8d44", "num": 152, "pinyin": "z\u012b", "tono": 1, "significado": "dinero", "trazos": 8},
    {"radical": "\u8eab", "num": 153, "pinyin": "sh\u0113n", "tono": 1, "significado": "cuerpo", "trazos": 7, "dominio": ["cuerpo", "yo", "personal"], "tecnico": ["body", "self", "身"]},
    {"radical": "\u8fb0", "num": 154, "pinyin": "ch\u00e9n", "tono": 2, "significado": "dragon", "trazos": 7, "dominio": ["drag\u00f3n", "imperio", "sabidur\u00eda"], "tecnico": ["车", "car", "vehicle"]},
    {"radical": "\u8fbb", "num": 155, "pinyin": "ch\u0113", "tono": 1, "significado": "carro", "trazos": 7, "dominio": ["carro", "veh\u00edculo", "transporte"], "tecnico": ["car", "vehicle", "chariot"]},
    {"radical": "\u8fcd", "num": 156, "pinyin": "xu\u00e0n", "tono": 4, "significado": "florecer", "trazos": 7},
    {"radical": "\u8fde", "num": 157, "pinyin": "li\u00e1n", "tono": 2, "significado": "unir", "trazos": 7, "dominio": ["uni\u00f3n", "conexi\u00f3n", "continuidad"], "tecnico": ["connect", "link", "连"]},
    {"radical": "\u8f9b", "num": 158, "pinyin": "x\u012bn", "tono": 1, "significado": "nuevo", "trazos": 7, "dominio": ["nuevo", "fresco", "reciente"], "tecnico": ["new", "fresh", "novel"]},
    {"radical": "\u8fdb", "num": 159, "pinyin": "j\u00ecn", "tono": 4, "significado": "avanzar", "trazos": 7, "dominio": ["avance", "progreso", "entrada"], "tecnico": ["advance", "enter", "进"]},
    {"radical": "\u90ce", "num": 160, "pinyin": "l\u00e0ng", "tono": 4, "significado": "onda", "trazos": 7},
    {"radical": "\u90fd", "num": 161, "pinyin": "d\u016b", "tono": 1, "significado": "capital", "trazos": 10},
    {"radical": "\u91cc", "num": 162, "pinyin": "l\u01d2", "tono": 3, "significado": "interior", "trazos": 7, "dominio": ["interior", "dentro", "interno"], "tecnico": ["inside", "里", "inner"]},
    {"radical": "\u91cd", "num": 163, "pinyin": "zh\u00f2ng", "tono": 4, "significado": "peso", "trazos": 9},
    {"radical": "\u91d1", "num": 167, "pinyin": "j\u012bn", "tono": 1, "significado": "oro", "trazos": 8, "dominio": ["oro", "metal", "dinero"], "tecnico": ["gold", "metal", "金"]},
    {"radical": "\u957f", "num": 168, "pinyin": "ch\u00e1ng", "tono": 2, "significado": "largo", "trazos": 8, "dominio": ["largo", "longitud", "permanencia"], "tecnico": ["long", "length", "长"]},
    {"radical": "\u95f0", "num": 169, "pinyin": "ch\u00e1ng", "tono": 2, "significado": "puerta", "trazos": 8},
    {"radical": "\u96b9", "num": 172, "pinyin": "y\u00e0", "tono": 4, "significado": "p\u00e1jaro", "trazos": 8},
    {"radical": "\u9700", "num": 176, "pinyin": "x\u016b", "tono": 1, "significado": "necesitar", "trazos": 8, "dominio": ["necesidad", "requerimiento", "demanda"], "tecnico": ["need", "require", "must"]},
    {"radical": "\u9752", "num": 174, "pinyin": "q\u012bng", "tono": 1, "significado": "azul/verde", "trazos": 8},
    {"radical": "\u9759", "num": 174, "pinyin": "j\u00ecng", "tono": 4, "significado": "tranquilo", "trazos": 8, "dominio": ["tranquilidad", "calma", "paz"], "tecnico": ["quiet", "静", "still"]},
    {"radical": "\u9762", "num": 176, "pinyin": "mi\u00e0n", "tono": 4, "significado": "cara", "trazos": 9},
    {"radical": "\u9773", "num": 177, "pinyin": "ji\u00e0n", "tono": 4, "significado": "犁", "trazos": 12},
    {"radical": "\u98ce", "num": 182, "pinyin": "f\u0113ng", "tono": 1, "significado": "viento", "trazos": 4, "dominio": ["viento", "cambio", "influencia"], "tecnico": ["wind", "fan", " 风"]},
    {"radical": "\u98df", "num": 184, "pinyin": "sh\u00ed", "tono": 2, "significado": "comida", "trazos": 7, "dominio": ["comida", "nutrici\u00f3n", "consumo"], "tecnico": ["food", "eat", "食"]},
    {"radical": "\u9996", "num": 185, "pinyin": "sh\u00f2u", "tono": 3, "significado": "cabeza", "trazos": 9, "dominio": ["cabeza", "l\u00edder", "inicio"], "tecnico": ["head", "首", "main"]},
    {"radical": "\u9a6c", "num": 187, "pinyin": "m\u01d9", "tono": 3, "significado": "caballo", "trazos": 10, "dominio": ["caballo", "velocidad", "nobleza"], "tecnico": ["horse", "马"]},
    {"radical": "\u9a7c", "num": 188, "pinyin": "lu\u00f2", "tono": 4, "significado": "camello", "trazos": 10},
    {"radical": "\u9a7e", "num": 189, "pinyin": "q\u016b", "tono": 1, "significado": "montar", "trazos": 15},
    {"radical": "\u9ad8", "num": 189, "pinyin": "g\u0101o", "tono": 1, "significado": "alto", "trazos": 10, "dominio": ["alto", "elevaci\u00f3n", "altura"], "tecnico": ["high", "tall", "高"]},
    {"radical": "\u9b3c", "num": 194, "pinyin": "gu\u01d2", "tono": 3, "significado": "fantasma", "trazos": 8, "dominio": ["fantasma", "esp\u00edritu", "oculto"], "tecnico": ["ghost", "鬼"]},
    {"radical": "\u9c7c", "num": 195, "pinyin": "y\u00fa", "tono": 2, "significado": "pez", "trazos": 11, "dominio": ["pez", "adaptabilidad", "fluidez"], "tecnico": ["fish", "鱼"]},
    {"radical": "\u9e1f", "num": 196, "pinyin": "ni\u01ceo", "tono": 3, "significado": "p\u00e1jaro", "trazos": 11, "dominio": ["p\u00e1jaro", "libertad", "mensaje"], "tecnico": ["bird", "鸟"]},
    {"radical": "\u9e7f", "num": 197, "pinyin": "l\u00f9", "tono": 4, "significado": "ciervo", "trazos": 11},
    {"radical": "\u9e93", "num": 198, "pinyin": "m\u00e0", "tono": 4, "significado": "sal", "trazos": 12},
    {"radical": "\u9ea6", "num": 199, "pinyin": "m\u00e0i", "tono": 4, "significado": "trigo", "trazos": 11},
    {"radical": "\u9ebb", "num": 200, "pinyin": "ma", "tono": 2, "significado": "c\u00e1\u00f1amo", "trazos": 11},
    {"radical": "\u9ece", "num": 201, "pinyin": "l\u00ed", "tono": 4, "significado": "negro", "trazos": 12, "dominio": ["negro", "oscuro", "noche"], "tecnico": ["black", "dark", "黄"]},
    {"radical": "\u9ed1", "num": 203, "pinyin": "h\u0113i", "tono": 1, "significado": "negro", "trazos": 12, "dominio": ["negro", "oscuridad", "secreto"], "tecnico": ["black", "dark", "黑"]},
    {"radical": "\u9f0b", "num": 207, "pinyin": "zh\u016b", "tono": 1, "significado": "cerdo", "trazos": 17},
    {"radical": "\u9f20", "num": 208, "pinyin": "sh\u00fa", "tono": 3, "significado": "rat\u00f3n", "trazos": 17, "dominio": ["rat\u00f3n", "sutil", "oculto"], "tecnico": ["mouse", "rat", "鼠标"]},
    {"radical": "\u9f7f", "num": 209, "pinyin": "n\u016d", "tono": 3, "significado": "nariz", "trazos": 11},
    {"radical": "\u9f80", "num": 210, "pinyin": "xi\u0101ng", "tono": 1, "significado": "olfato", "trazos": 12},
    {"radical": "\u9f99", "num": 212, "pinyin": "l\u00f3ng", "tono": 2, "significado": "drag\u00f3n", "trazos": 16, "dominio": ["drag\u00f3n", "poder", "sabidur\u00eda", "imperio"], "tecnico": ["龙", "dragon", "long"]},
    {"radical": "\u9f9f", "num": 213, "pinyin": "gu\u012b", "tono": 1, "significado": "tortuga", "trazos": 13, "dominio": ["tortuga", "longevidad", "sabidur\u00eda"], "tecnico": ["turtle", "龟"]},
    {"radical": "\u9fa5", "num": 214, "pinyin": "hu\u00f2", "tono": 4, "significado": "cilindro", "trazos": 10},
]

# ══════════════════════════════════════════════════════════════════════════════
# CARACTERES COMUNES (no radicales) con contexto emocional y técnico
# ══════════════════════════════════════════════════════════════════════════════

COMMON_CHARS: List[Dict] = [
    {"hanzi": "\u6c38", "pinyin": "y\u014dng", "tono": 3, "significado": "eternidad", "dominio": ["eternidad", "para siempre"], "emocion": ["amor eterno", "lealtad"], "tecnico": ["forever", "永"]},
    {"hanzi": "\u795d", "pinyin": "zh\u00f9", "tono": 4, "significado": "bendecir", "dominio": ["bendici\u00f3n", "buena fortuna"], "emocion": ["gratitud", "alivio"], "tecnico": ["bless", "祝"]},
    {"hanzi": "\u798f", "pinyin": "f\u00fa", "tono": 2, "significado": "felicidad", "dominio": ["felicidad", "buena fortuna"], "emocion": ["felicidad", "alegr\u00eda"], "tecnico": ["福", "fortune"]},
    {"hanzi": "\u5584", "pinyin": "sh\u00e0n", "tono": 4, "significado": "bondad", "dominio": ["bondad", "virtud"], "emocion": ["compasi\u00f3n", "ternura"], "tecnico": ["善", "good"]},
    {"hanzi": "\u771f", "pinyin": "zh\u0113n", "tono": 1, "significado": "verdad", "dominio": ["verdad", "autenticidad"], "emocion": ["honestidad", "sinceridad"], "tecnico": ["true", "real", "真"]},
    {"hanzi": "\u5fc3", "pinyin": "x\u012bn", "tono": 1, "significado": "coraz\u00f3n", "dominio": ["coraz\u00f3n", "mente", "emoci\u00f3n"], "emocion": ["todo lo emocional"], "tecnico": ["heart", "mind", "心"]},
    {"hanzi": "\u7231", "pinyin": "\u00e0i", "tono": 4, "significado": "amor", "dominio": ["amor", "cari\u00f1o", "afecto"], "emocion": ["amor", "ternura", "devoci\u00f3n"], "tecnico": ["love", "爱"]},
    {"hanzi": "\u5f85", "pinyin": "d\u00e0i", "tono": 4, "significado": "esperar", "dominio": ["espera", "paciencia"], "emocion": ["esperanza", "ansiedad"], "tecnico": ["wait", "await", "待"]},
    {"hanzi": "\u672c", "pinyin": "b\u0113n", "tono": 3, "significado": "origen", "dominio": ["origen", "base", "esencia"], "emocion": ["nostalgia", "identidad"], "tecnico": ["origin", "base", "本"]},
    {"hanzi": "\u540c", "pinyin": "t\u00f3ng", "tono": 2, "significado": "mismo", "dominio": ["igualdad", "simpat\u00eda"], "emocion": ["conexi\u00f3n", "pertenencia"], "tecnico": ["same", "同"]},
    {"hanzi": "\u5b57", "pinyin": "z\u00ec", "tono": 4, "significado": "car\u00e1cter", "dominio": ["car\u00e1cter", "escritura", "palabra"], "emocion": ["identidad", "palabra"], "tecnico": ["char", "字", "character"]},
    {"hanzi": "\u8bed", "pinyin": "y\u01d4", "tono": 3, "significado": "lengua/palabra", "dominio": ["lengua", "habla", "idioma"], "emocion": ["comunicaci\u00f3n", "expresi\u00f3n"], "tecnico": ["language", "word", "语"]},
    {"hanzi": "\u547d", "pinyin": "m\u00ecng", "tono": 4, "significado": "orden/vida", "dominio": ["orden", "destino", "misi\u00f3n"], "emocion": ["determinaci\u00f3n", "prop\u00f3sito"], "tecnico": ["order", "命", "destiny"]},
    {"hanzi": "\u8d75", "pinyin": "zh\u00e0o", "tono": 4, "significado": "llamar", "dominio": ["llamada", "invocaci\u00f3n"], "emocion": ["anhelo", "b\u00fasqueda"], "tecnico": ["call", "invoke", "召"]},
    {"hanzi": "\u5149", "pinyin": "gu\u0101ng", "tono": 1, "significado": "luz", "dominio": ["luz", "claridad", "esplendor"], "emocion": ["alegr\u00eda", "esperanza", "claridad"], "tecnico": ["light", "光", "bright"]},
    {"hanzi": "\u4eae", "pinyin": "li\u00e0ng", "tono": 4, "significado": "brillante", "dominio": ["brillo", "luminosidad"], "emocion": ["alegr\u00eda", "energ\u00eda"], "tecnico": ["亮", "bright", "shine"]},
    {"hanzi": "\u6674", "pinyin": "q\u00edng", "tono": 2, "significado": "despejado", "dominio": ["despejado", "tranquilidad"], "emocion": ["calma", "alivio"], "tecnico": ["clear", "晴", "sunny"]},
    {"hanzi": "\u96e8", "pinyin": "y\u01d4", "tono": 3, "significado": "lluvia", "dominio": ["lluvia", "tristeza", "renovaci\u00f3n"], "emocion": ["tristeza", "nostalgia", "melancol\u00eda"], "tecnico": ["rain", "雨"]},
    {"hanzi": "\u98ce", "pinyin": "f\u0113ng", "tono": 1, "significado": "viento", "dominio": ["viento", "cambio", "libertad"], "emocion": ["libertad", "cambio"], "tecnico": ["wind", "风", "breeze"]},
    {"hanzi": "\u96f7", "pinyin": "l\u00e9i", "tono": 2, "significado": "trueno", "dominio": ["trueno", "tormenta", " IRA"], "emocion": ["ira", "miedo", "vigor"], "tecnico": ["thunder", "雷"]},
    {"hanzi": "\u96ea", "pinyin": "xu\u01d2", "tono": 3, "significado": "nieve", "dominio": ["nieve", "pureza", "fr\u00edo"], "emocion": ["pureza", "soledad", "calma"], "tecnico": ["snow", "雪"]},
    {"hanzi": "\u7075", "pinyin": "l\u00edng", "tono": 2, "significado": "esp\u00edritu", "dominio": ["esp\u00edritu", "alma", "inteligencia"], "emocion": ["alma", "vitalidad"], "tecnico": ["spirit", "灵", "soul"]},
    {"hanzi": "\u9b42", "pinyin": "h\u00fan", "tono": 2, "significado": "alma", "dominio": ["alma", "esp\u00edritu", "conciencia"], "emocion": ["alma", "identidad profunda"], "tecnico": ["soul", "魂", "spirit"]},
    {"hanzi": "\u7075", "pinyin": "l\u00edng", "tono": 2, "significado": "alma", "dominio": ["alma", "conciencia"], "emocion": ["alma"], "tecnico": ["灵"]},
    {"hanzi": "\u5b88", "pinyin": "sh\u01d2u", "tono": 3, "significado": "guardar", "dominio": ["protecci\u00f3n", "custodia", "mantener"], "emocion": ["protecci\u00f3n", "lealtad"], "tecnico": ["guard", "守", "protect"]},
    {"hanzi": "\u62a4", "pinyin": "h\u00f9", "tono": 4, "significado": "proteger", "dominio": ["protecci\u00f3n", "cuidado"], "emocion": ["cuidado", "protecci\u00f3n"], "tecnico": ["protect", "护"]},
    {"hanzi": "\u80fd", "pinyin": "n\u00e9ng", "tono": 2, "significado": "poder", "dominio": ["capacidad", "habilidad", "poder"], "emocion": ["confianza", "determinaci\u00f3n"], "tecnico": ["can", "能", "ability"]},
    {"hanzi": "\u4e1c", "pinyin": "d\u014dng", "tono": 1, "significado": "este/oriente", "dominio": ["este", "amanecer", "comienzo"], "emocion": ["esperanza", "inicio"], "tecnico": ["east", "东"]},
    {"hanzi": "\u897f", "pinyin": "x\u012b", "tono": 1, "significado": "oeste", "dominio": ["oeste", "atardecer", "fin"], "emocion": ["nostalgia", "reflexi\u00f3n"], "tecnico": ["west", "西"]},
    {"hanzi": "\u5357", "pinyin": "n\u00e1n", "tono": 2, "significado": "sur", "dominio": ["sur", "calidez"], "emocion": ["calidez", "esperanza"], "tecnico": ["south", "南"]},
    {"hanzi": "\u5317", "pinyin": "b\u011be", "tono": 3, "significado": "norte", "dominio": ["norte", "fr\u00edo", "lealtad"], "emocion": ["soledad", "lealtad"], "tecnico": ["north", "北"]},
    {"hanzi": "\u4e0a", "pinyin": "sh\u00e0ng", "tono": 4, "significado": "arriba", "dominio": ["arriba", "superior", "subir"], "emocion": ["aspiraci\u00f3n", "elevaci\u00f3n"], "tecnico": ["up", "上", "above"]},
    {"hanzi": "\u4e0b", "pinyin": "xi\u00e0", "tono": 4, "significado": "abajo", "dominio": ["abajo", "inferior", "descender"], "emocion": ["humildad", "ca\u00edda"], "tecnico": ["down", "下", "below"]},
    {"hanzi": "\u524d", "pinyin": "qi\u00e1n", "tono": 2, "significado": "adelante", "dominio": ["adelante", "futuro", "progreso"], "emocion": ["esperanza", "anticipaci\u00f3n"], "tecnico": ["forward", "前", "before"]},
    {"hanzi": "\u540e", "pinyin": "h\u00f2u", "tono": 4, "significado": "detr\u00e1s", "dominio": ["detr\u00e1s", "pasado", "despu\u00e9s"], "emocion": ["nostalgia", "arrepentimiento"], "tecnico": ["after", "后", "behind"]},
    {"hanzi": "\u5185", "pinyin": "n\u00e8i", "tono": 4, "significado": "dentro", "dominio": ["interior", "dentro"], "emocion": ["introspecci\u00f3n"], "tecnico": ["inside", "内", "inner"]},
    {"hanzi": "\u5916", "pinyin": "w\u00e0i", "tono": 4, "significado": "fuera", "dominio": ["exterior", "fuera"], "emocion": ["expansi\u00f3n"], "tecnico": ["outside", "外", "outer"]},
    {"hanzi": "\u52a0", "pinyin": "ji\u0101", "tono": 1, "significado": "a\u00f1adir", "dominio": ["adici\u00f3n", "aumentar"], "emocion": ["esperanza", "crecimiento"], "tecnico": ["add", "加", "plus"]},
    {"hanzi": "\u51cf", "pinyin": "ji\u01cen", "tono": 3, "significado": "reducir", "dominio": ["reducci\u00f3n", "disminuci\u00f3n"], "emocion": ["alivio", "simplificaci\u00f3n"], "tecnico": ["reduce", "减", "minus"]},
    {"hanzi": "\u6210", "pinyin": "ch\u00e9ng", "tono": 2, "significado": "lograr", "dominio": ["\u00e9xito", "logro", "completar"], "emocion": ["satisfacci\u00f3n", "orgullo"], "tecnico": ["achieve", "成", "complete"]},
    {"hanzi": "\u5931", "pinyin": "sh\u012b", "tono": 1, "significado": "perder/fallo", "dominio": ["fracaso", "p\u00e9rdida", "error"], "emocion": ["dolor", "frustraci\u00f3n", "arrepentimiento"], "tecnico": ["fail", "lose", "失"]},
    {"hanzi": "\u5f97", "pinyin": "d\u00e9", "tono": 2, "significado": "obtener", "dominio": ["obtenci\u00f3n", "ganancia"], "emocion": ["satisfacci\u00f3n", "alivio"], "tecnico": ["get", "得", "obtain"]},
    {"hanzi": "\u8c6b", "pinyin": "j\u00ed", "tono": 2, "significado": "urgente", "dominio": ["urgencia", "prisa"], "emocion": ["ansiedad", "urgencia"], "tecnico": ["urgent", "急", "hurry"]},
    {"hanzi": "\u65f6", "pinyin": "sh\u00ed", "tono": 2, "significado": "tiempo", "dominio": ["tiempo", "\u00e9poca", "momento"], "emocion": ["reflexi\u00f3n", "nostalgia"], "tecnico": ["time", "时", "temporal"]},
    {"hanzi": "\u7a7a", "pinyin": "k\u014dng", "tono": 1, "significado": "vac\u00edo", "dominio": ["vacio", "ausencia", "libertad"], "emocion": ["soledad", "libertad", "paz"], "tecnico": ["empty", "空", "null"]},
    {"hanzi": "\u5b9e", "pinyin": "sh\u00ed", "tono": 2, "significado": "real", "dominio": ["realidad", "verdad", "pr\u00e1ctico"], "emocion": ["honestidad"], "tecnico": ["real", "实", "actual"]},
    {"hanzi": "\u504f", "pinyin": "pi\u0101n", "tono": 1, "significado": "sesgar", "dominio": ["sesgo", "desviaci\u00f3n"], "emocion": ["subjetividad"], "tecnico": ["bias", "偏", "skew"]},
    {"hanzi": "\u7ec3", "pinyin": "li\u00e0n", "tono": 4, "significado": "practicar", "dominio": ["pr\u00e1ctica", "ejercicio", "entrenamiento"], "emocion": ["disciplina", "perseverancia"], "tecnico": ["practice", "练", "train"]},
    {"hanzi": "\u601d", "pinyin": "s\u012b", "tono": 1, "significado": "pensar", "dominio": ["pensamiento", "reflexi\u00f3n", "idea"], "emocion": ["reflexi\u00f3n", "contemplaci\u00f3n"], "tecnico": ["think", "思", "thought"]},
    {"hanzi": "\u60f3", "pinyin": "xi\u01d3ng", "tono": 3, "significado": "pensar/extra\u00f1ar", "dominio": ["pensamiento", "deseo", " añoranza"], "emocion": ["añoranza", "deseo"], "tecnico": ["think", "想", "miss"]},
    {"hanzi": "\u5fd8", "pinyin": "w\u00e0ng", "tono": 4, "significado": "olvidar", "dominio": ["olvido", "negligencia"], "emocion": ["alivio", "p\u00e9rdida"], "tecnico": ["forget", "忘"]},
    {"hanzi": "\u8bb0", "pinyin": "j\u00ec", "tono": 4, "significado": "recordar", "dominio": ["memoria", "registro"], "emocion": ["nostalgia", "gratitud"], "tecnico": ["remember", "记"]},
    {"hanzi": "\u9519", "pinyin": "cu\u00f2", "tono": 4, "significado": "error", "dominio": ["error", "equivocaci\u00f3n", "fallo"], "emocion": ["frustraci\u00f3n", "arrepentimiento"], "tecnico": ["error", "mistake", "错"]},
    {"hanzi": "\u6b63", "pinyin": "zh\u00e8ng", "tono": 4, "significado": "correcto", "dominio": ["correoci\u00f3n", "rectitud"], "emocion": ["satisfacci\u00f3n"], "tecnico": ["correct", "right", "正"]},
    {"hanzi": "\u8f93", "pinyin": "sh\u00f9", "tono": 4, "significado": "transportar", "dominio": ["transporte", "transmisi\u00f3n"], "emocion": ["env\u00edo"], "tecnico": ["transport", "输", "transmit"]},
    {"hanzi": "\u6536", "pinyin": "sh\u014du", "tono": 1, "significado": "recibir", "dominio": ["rece pci\u00f3n", "cobro"], "emocion": ["recepci\u00f3n", "alivio"], "tecnico": ["receive", "收", "get"]},
    {"hanzi": "\u53d1", "pinyin": "f\u0101", "tono": 1, "significado": "enviar/ocurrir", "dominio": ["env\u00edo", "ocurrencia", "desarrollo"], "emocion": ["iniciativa"], "tecnico": ["send", "发", "emit"]},
    {"hanzi": "\u5e94", "pinyin": "y\u012bng", "tono": 1, "significado": "deber", "dominio": ["deber", "responder", "corresponder"], "emocion": ["responsabilidad"], "tecnico": ["should", "应", "respond"]},
    {"hanzi": "\u5c31", "pinyin": "ji\u00f9", "tono": 4, "significado": "justo/as\u00ed", "dominio": ["precisamente", "simplemente"], "emocion": ["determinaci\u00f3n"], "tecnico": ["just", "就", "then"]},
    {"hanzi": "\u4e0d", "pinyin": "b\u00f9", "tono": 4, "significado": "no", "dominio": ["negaci\u00f3n"], "emocion": ["negaci\u00f3n"], "tecnico": ["not", "不", "no"]},
    {"hanzi": "\u4e86", "pinyin": "le", "tono": 5, "significado": "completado", "dominio": ["completado", "part\u00edcula aspectual"], "emocion": ["alivio", "conclusi\u00f3n"], "tecnico": ["done", "了", "finish"]},
    {"hanzi": "\u8fd9", "pinyin": "zh\u00e8", "tono": 4, "significado": "este", "dominio": ["este", "esto"], "emocion": ["presente"], "tecnico": ["this", "这"]},
    {"hanzi": "\u90a3", "pinyin": "n\u00e0", "tono": 4, "significado": "ese", "dominio": ["ese", "aquello"], "emocion": ["distancia"], "tecnico": ["that", "那"]},
    {"hanzi": "\u4ec5", "pinyin": "j\u01d2n", "tono": 3, "significado": "solo", "dominio": ["soledad", "exclusividad"], "emocion": ["soledad", "uniqueness"], "tecnico": ["only", "仅", "just"]},
    {"hanzi": "\u591a", "pinyin": "du\u014d", "tono": 1, "significado": "mucho", "dominio": ["cantidad", "abundancia"], "emocion": ["abundancia"], "tecnico": ["many", "多"]},
    {"hanzi": "\u5c11", "pinyin": "sh\u01ceo", "tono": 4, "significado": "poco", "dominio": ["escasez", "paucidad"], "emocion": ["escasez"], "tecnico": ["few", "少"]},
    {"hanzi": "\u5168", "pinyin": "qu\u00e1n", "tono": 2, "significado": "todo", "dominio": ["totalidad", "completitud"], "emocion": ["totalidad"], "tecnico": ["all", "全", "whole"]},
    {"hanzi": "\u90e8", "pinyin": "b\u00f9", "tono": 4, "significado": "parte", "dominio": ["parte", "secci\u00f3n"], "emocion": ["fragmentaci\u00f3n"], "tecnico": ["part", "部"]},
    {"hanzi": "\u517c", "pinyin": "ji\u0101n", "tono": 1, "significado": "simult\u00e1neamente", "dominio": ["simultaneidad"], "emocion": ["complejidad"], "tecnico": ["both", "兼", "and"]},
    {"hanzi": "\u76f8", "pinyin": "xi\u0101ng", "tono": 1, "significado": "mutuamente", "dominio": ["reciprocidad", "correlaci\u00f3n"], "emocion": ["conexi\u00f3n"], "tecnico": ["mutual", "相"]},
    {"hanzi": "\u65e0", "pinyin": "w\u00fa", "tono": 2, "significado": "sin", "dominio": ["ausencia", "nada"], "emocion": ["vac\u00edo", "libertad"], "tecnico": ["without", "无", "none"]},
    {"hanzi": "\u6709", "pinyin": "y\u01d2u", "tono": 3, "significado": "tener/existir", "dominio": ["posesi\u00f3n", "existencia"], "emocion": ["posesi\u00f3n", "satisfacci\u00f3n"], "tecnico": ["have", "有", "exist"]},
    {"hanzi": "\u4e3a", "pinyin": "w\u00e8i", "tono": 4, "significado": "por/ser", "dominio": ["prop\u00f3sito", "raz\u00f3n"], "emocion": ["prop\u00f3sito"], "tecnico": ["for", "为", "cause"]},
    {"hanzi": "\u4f5c", "pinyin": "zu\u00f2", "tono": 4, "significado": "hacer", "dominio": ["acci\u00f3n", "creaci\u00f3n"], "emocion": ["creaci\u00f3n", "iniciativa"], "tecnico": ["do", "作", "make"]},
    {"hanzi": "\u89c1", "pinyin": "ji\u00e0n", "tono": 4, "significado": "ver", "dominio": ["visi\u00f3n", "encuentro"], "emocion": ["descubrimiento"], "tecnico": ["see", "见"]},
    {"hanzi": "\u95ee", "pinyin": "w\u00e8n", "tono": 4, "significado": "preguntar", "dominio": ["pregunta", "interrogaci\u00f3n"], "emocion": ["curiosidad"], "tecnico": ["ask", "问"]},
    {"hanzi": "\u8bf4", "pinyin": "shu\u014d", "tono": 1, "significado": "decir", "dominio": ["habla", "explicaci\u00f3n"], "emocion": ["comunicaci\u00f3n"], "tecnico": ["say", "说"]},
    {"hanzi": "\u8cbb", "pinyin": "f\u00e8i", "tono": 4, "significado": "gastar", "dominio": ["gasto", "consumo"], "emocion": ["sacrificio"], "tecnico": ["spend", "费"]},
    {"hanzi": "\u7528", "pinyin": "y\u00f2ng", "tono": 4, "significado": "usar", "dominio": ["uso", "utilizaci\u00f3n"], "emocion": ["utilidad"], "tecnico": ["use", "用"]},
    {"hanzi": "\u5f00", "pinyin": "k\u0101i", "tono": 1, "significado": "abrir", "dominio": ["apertura", "inicio", "comienzo"], "emocion": ["iniciativa"], "tecnico": ["open", "开"]},
    {"hanzi": "\u5173", "pinyin": "gu\u0101n", "tono": 1, "significado": "cerrar/conectar", "dominio": ["cierre", "conexi\u00f3n", "relaci\u00f3n"], "emocion": ["conexi\u00f3n", "responsabilidad"], "tecnico": ["close", "关", "concern"]},
    {"hanzi": "\u65e5", "pinyin": "r\u00ec", "tono": 4, "significado": "d\u00eda/sol", "dominio": ["d\u00eda", "sol", "tiempo"], "emocion": ["tiempo"], "tecnico": ["day", "日"]},
    {"hanzi": "\u6708", "pinyin": "yu\u00e8", "tono": 4, "significado": "luna/mes", "dominio": ["luna", "mes", "ciclos"], "emocion": ["ciclos", "nostalgia"], "tecnico": ["month", "月"]},
    {"hanzi": "\u5e74", "pinyin": "ni\u00e1n", "tono": 2, "significado": "a\u00f1o", "dominio": ["a\u00f1o", "tiempo", "edad"], "emocion": ["tiempo", "envejecimiento"], "tecnico": ["year", "年"]},
    {"hanzi": "\u65f6", "pinyin": "sh\u00ed", "tono": 2, "significado": "hora", "dominio": ["hora", "momento", "tiempo"], "emocion": ["tiempo"], "tecnico": ["hour", "时"]},
    {"hanzi": "\u5206", "pinyin": "f\u0113n", "tono": 1, "significado": "dividir", "dominio": ["divisi\u00f3n", "parte", "separaci\u00f3n"], "emocion": ["separaci\u00f3n"], "tecnico": ["divide", "分", "split"]},
    {"hanzi": "\u5408", "pinyin": "h\u00e9", "tono": 2, "significado": "unir", "dominio": ["uni\u00f3n", "harmon\u00eda"], "emocion": ["harmon\u00eda"], "tecnico": ["join", "合", "combine"]},
    {"hanzi": "\u957f", "pinyin": "ch\u00e1ng", "tono": 2, "significado": "largo", "dominio": ["longitud", "permanencia"], "emocion": ["persistencia"], "tecnico": ["long", "长"]},
    {"hanzi": "\u77ed", "pinyin": "du\u01cen", "tono": 3, "significado": "corto", "dominio": ["brevedad"], "emocion": ["inmediatez"], "tecnico": ["short", "短"]},
    {"hanzi": "\u9ad8", "pinyin": "g\u0101o", "tono": 1, "significado": "alto", "dominio": ["altura", "excelencia"], "emocion": ["aspiraci\u00f3n"], "tecnico": ["high", "高"]},
    {"hanzi": "\u4f4e", "pinyin": "d\u012b", "tono": 1, "significado": "bajo", "dominio": ["baja altura", "humildad"], "emocion": ["humildad"], "tecnico": ["low", "低"]},
    {"hanzi": "\u65b9", "pinyin": "f\u0101ng", "tono": 1, "significado": "cuadrado/m\u00e9todo", "dominio": ["m\u00e9todo", "direcci\u00f3n"], "emocion": ["estrategia"], "tecnico": ["method", "方", "square"]},
    {"hanzi": "\u5706", "pinyin": "yu\u00e1n", "tono": 2, "significado": "redondo", "dominio": ["circular", "completitud"], "emocion": ["completitud"], "tecnico": ["round", "圆"]},
    {"hanzi": "\u4e49", "pinyin": "y\u00ec", "tono": 4, "significado": "justicia/significado", "dominio": ["significado", "justicia", "deber"], "emocion": ["moralidad"], "tecnico": ["meaning", "义"]},
    {"hanzi": "\u4e4b", "pinyin": "zh\u012b", "tono": 1, "significado": "de/esto", "dominio": ["part\u00edcula posesiva"], "emocion": ["conexi\u00f3n"], "tecnico": ["of", "之"]},
    {"hanzi": "\u4e5f", "pinyin": "y\u01d2", "tono": 3, "significado": "tambi\u00e9n", "dominio": ["adici\u00f3n", "tambi\u00e9n"], "emocion": ["conexi\u00f3n"], "tecnico": ["also", "也"]},
    {"hanzi": "\u5df2", "pinyin": "y\u01d2", "tono": 3, "significado": "ya", "dominio": ["completado", "pasado"], "emocion": ["conclusi\u00f3n"], "tecnico": ["already", "已"]},
    {"hanzi": "\u4ece", "pinyin": "c\u00f3ng", "tono": 2, "significado": "desde", "dominio": ["origen", "procedencia"], "emocion": ["origen"], "tecnico": ["from", "从"]},
    {"hanzi": "\u5411", "pinyin": "xi\u00e0ng", "tono": 4, "significado": "hacia", "dominio": ["direcci\u00f3n", "tendencia"], "emocion": ["aspiraci\u00f3n"], "tecnico": ["towards", "向"]},
    {"hanzi": "\u56f0", "pinyin": "k\u00f9n", "tono": 4, "significado": "dificultad", "dominio": ["dificultad", "obst\u00e1culo"], "emocion": ["frustraci\u00f3n", "ansiedad"], "tecnico": ["difficulty", "困"]},
    {"hanzi": "\u968f", "pinyin": "su\u00ed", "tono": 2, "significado": "seguir", "dominio": ["seguimiento", "conforme"], "emocion": ["adaptabilidad"], "tecnico": ["follow", "随"]},
    {"hanzi": "\u968f", "pinyin": "su\u00ed", "tono": 2, "significado": "conforme", "dominio": ["adhesi\u00f3n"], "emocion": ["aceptaci\u00f3n"], "tecnico": ["随"]},
    {"hanzi": "\u56e0", "pinyin": "y\u012bn", "tono": 1, "significado": "causa", "dominio": ["causa", "raz\u00f3n"], "emocion": ["l\u00f3gica"], "tecnico": ["because", "因"]},
    {"hanzi": "\u6240", "pinyin": "su\u01d2", "tono": 3, "significado": "lugar donde", "dominio": ["lugar", "todo lo que"], "emocion": ["omnipresencia"], "tecnico": ["place", "所"]},
    {"hanzi": "\u4ea4", "pinyin": "ji\u0101o", "tono": 1, "significado": "entregar/cruzar", "dominio": ["interacci\u00f3n", "entrega"], "emocion": ["negociaci\u00f3n"], "tecnico": ["交", "交"]},
    {"hanzi": "\u901a", "pinyin": "t\u014dng", "tono": 1, "significado": "atrav\u00e9s/comunicar", "dominio": ["comunicaci\u00f3n", "conexi\u00f3n"], "emocion": ["conexi\u00f3n"], "tecnico": ["通", "through", "connect"]},
    {"hanzi": "\u8fc7", "pinyin": "gu\u00f2", "tono": 4, "significado": "pasar", "dominio": ["proceso", "transici\u00f3n"], "emocion": ["transici\u00f3n"], "tecnico": ["pass", "过"]},
    {"hanzi": "\u8fdb", "pinyin": "j\u00ecn", "tono": 4, "significado": "entrar/avanzar", "dominio": ["entrada", "progreso"], "emocion": ["avance"], "tecnico": ["enter", "进"]},
    {"hanzi": "\u51fa", "pinyin": "ch\u016b", "tono": 1, "significado": "salir", "dominio": ["salida", "expulsi\u00f3n"], "emocion": ["liberaci\u00f3n"], "tecnico": ["exit", "出"]},
    {"hanzi": "\u56de", "pinyin": "hu\u00ed", "tono": 2, "significado": "volver", "dominio": ["retorno", "respuesta"], "emocion": ["retorno", "nostalgia"], "tecnico": ["return", "回"]},
    {"hanzi": "\u6765", "pinyin": "l\u00e1i", "tono": 2, "significado": "venir", "dominio": ["llegada", "futuro"], "emocion": ["anticipaci\u00f3n"], "tecnico": ["come", "来"]},
    {"hanzi": "\u53bb", "pinyin": "q\u00f9", "tono": 4, "significado": "ir", "dominio": ["partida", "acci\u00f3n"], "emocion": ["acci\u00f3n"], "tecnico": ["go", "去"]},
    {"hanzi": "\u8fd8", "pinyin": "hu\u00e1n", "tono": 2, "significado": "todav\u00eda/volver", "dominio": ["retorno", "continuaci\u00f3n"], "emocion": ["persistencia"], "tecnico": ["still", "还", "return"]},
    {"hanzi": "\u5c3d", "pinyin": "j\u01d2n", "tono": 4, "significado": "hasta", "dominio": ["l\u00edmite", "completud"], "emocion": ["determinaci\u00f3n"], "tecnico": ["until", "尽"]},
    {"hanzi": "\u6b7b", "pinyin": "s\u01d2", "tono": 3, "significado": "morir", "dominio": ["muerte", "fin"], "emocion": ["miedo", "tristeza"], "tecnico": ["die", "死"]},
    {"hanzi": "\u6d77", "pinyin": "h\u01d2i", "tono": 3, "significado": "mar", "dominio": ["mar", "vastedad", "abismo"], "emocion": ["vasta", "melancol\u00eda"], "tecnico": ["sea", "海"]},
    {"hanzi": "\u5c71", "pinyin": "sh\u0101n", "tono": 1, "significado": "monta\u00f1a", "dominio": ["monta\u00f1a", "estabilidad", "altura"], "emocion": ["estabilidad"], "tecnico": ["mountain", "山"]},
    {"hanzi": "\u6c34", "pinyin": "shu\u01d2", "tono": 3, "significado": "agua", "dominio": ["agua", "fluidez", "adaptabilidad"], "emocion": ["fluidez"], "tecnico": ["water", "水"]},
    {"hanzi": "\u706b", "pinyin": "hu\u01d2", "tono": 3, "significado": "fuego", "dominio": ["fuego", "energ\u00eda", "destrucci\u00f3n"], "emocion": ["pasión", "ira"], "tecnico": ["fire", "火"]},
    {"hanzi": "\u571f", "pinyin": "t\u01d2", "tono": 3, "significado": "tierra", "dominio": ["tierra", "suelo", "base"], "emocion": ["estabilidad"], "tecnico": ["earth", "土"]},
    {"hanzi": "\u91d1", "pinyin": "j\u012bn", "tono": 1, "significado": "oro", "dominio": ["oro", "metal", "valor"], "emocion": ["codicia", "valor"], "tecnico": ["gold", "金"]},
    {"hanzi": "\u6728", "pinyin": "m\u00f9", "tono": 4, "significado": "\u00e1rbol/madera", "dominio": ["\u00e1rbol", "naturaleza", "flexibilidad"], "emocion": ["flexibilidad"], "tecnico": ["wood", "木", "tree"]},
]

# ══════════════════════════════════════════════════════════════════════════════
# CHENGYU (PROVERBIOS CHINOS) — Base completa
# ══════════════════════════════════════════════════════════════════════════════

CHENGYU: List[Dict] = [
    {"chengyu": "一心一意", "pinyin": "yī xīn yī yì", "significado": "una mente, un prop\u00f3sito \u00fanico", "dominio": ["concentraci\u00f3n", "fidelidad"], "emocion": ["determinaci\u00f3n"], "ejemplo": "一心一意地写代码 — programar con una mente"},
    {"chengyu": "永生永世", "pinyin": "y\u014dng sh\u0113ng y\u014dng sh\u00ec", "significado": "por siempre, eternamente", "dominio": ["eternidad", "compromiso"], "emocion": ["amor eterno", "lealtad"], "ejemplo": "永生永世在一起 — estar juntos por siempre"},
    {"chengyu": "天长地久", "pinyin": "ti\u0101n ch\u00e1ng d\u00ec ji\u01d4", "significado": "tan largo como el cielo y la tierra", "dominio": ["eternidad", "permanencia"], "emocion": ["amor duradero"], "ejemplo": "我们的友谊天长地久 — nuestra amistad dura como el cielo"},
    {"chengyu": "破茧成蝶", "pinyin": "p\u00f2 ji\u01cen ch\u00e9ng di\u00e9", "significado": "romper el capullo y convertirse en mariposa", "dominio": ["metamorfosis", "transformaci\u00f3n"], "emocion": ["esperanza", "renacimiento"], "ejemplo": "他从失败中破茧成蝶 — se transform\u00f3 del fracaso"},
    {"chengyu": "水到渠成", "pinyin": "shu\u01d2 d\u00e0o q\u00fa ch\u00e9ng", "significado": "el agua llega y el canal se forma", "dominio": ["naturalidad", "progreso org\u00e1nico"], "emocion": ["calma", "confianza"], "ejemplo": "代码写到一定程度，水到渠成 — cuando el c\u00f3digo madura, fluye solo"},
    {"chengyu": "火中取栗", "pinyin": "hu\u01d2 zh\u014dng q\u01d9 l\u00ec", "significado": "sacar las castañas del fuego", "dominio": ["riesgo", "sacrificio"], "emocion": ["ira", "frustraci\u00f3n"], "ejemplo": "为别人火中取栗 — sacrificarte por otros"},
    {"chengyu": "眼观六路", "pinyin": "y\u01cen gu\u0101n li\u00f9 l\u00f9", "significado": "ver en seis direcciones", "dominio": ["vigilancia", "atenci\u00f3n total"], "emocion": ["alerta", "cuidado"], "ejemplo": "眼观六路，耳听八方 — vigilar todo"},
    {"chengyu": "稳如泰山", "pinyin": "w\u0113n r\u00fa t\u00e0i sh\u0101n", "significado": "estable como el Monte Tai", "dominio": ["estabilidad", "firmeza"], "emocion": ["calma", "confianza"], "ejemplo": "系统在负载下稳如泰山 — el sistema es estable bajo carga"},
    {"chengyu": "力挽狂澜", "pinyin": "l\u00ec w\u01cen ku\u00e1ng l\u00e1n", "significado": "detener la tormenta con fuerza", "dominio": ["intervenci\u00f3n heroica", "control"], "emocion": ["determinaci\u00f3n", "coraje"], "ejemplo": "在危机中力挽狂澜 — salvar la situaci\u00f3n en crisis"},
    {"chengyu": "实事求是", "pinyin": "sh\u00ed sh\u00ec qi\u00fa sh\u00ec", "significado": "buscar la verdad de los hechos", "dominio": ["verdad", "pragmatismo"], "emocion": ["honestidad"], "ejemplo": "我们实事求是地分析问题 — analicemos los hechos"},
    {"chengyu": "心心相印", "pinyin": "x\u012bn x\u012bn xi\u0101ng y\u00ecn", "significado": "corazones que se sellan", "dominio": ["conexi\u00f3n profunda", "intimidad"], "emocion": ["amor", "conexi\u00f3n"], "ejemplo": "我们心心相印 — nuestros corazones se entienden"},
    {"chengyu": "旭日东升", "pinyin": "x\u00f9 r\u00ec d\u014dng sh\u0113ng", "significado": "el sol asciende por el este", "dominio": ["amanecer", "nuevo comienzo"], "emocion": ["esperanza", "alegr\u00eda"], "ejemplo": "项目如旭日东升 — el proyecto nace con energ\u00eda"},
    {"chengyu": "月明星稀", "pinyin": "yu\u00e8 m\u00edng x\u012bng x\u012b", "significado": "luna brillante, estrellas escasas", "dominio": ["tranquilidad nocturna", "soledad"], "emocion": ["tristeza", "calma"], "ejemplo": "月明星稀的夜晚 — noches tranquilas bajo la luna"},
    {"chengyu": "起死回生", "pinyin": "q\u01d9 s\u01d9 hu\u00ed sh\u0113ng", "significado": "volver de la muerte a la vida", "dominio": ["resurrecci\u00f3n", "recuperaci\u00f3n"], "emocion": ["alivio", "miedo"], "ejemplo": "系统在崩溃后起死回生 — el sistema se recuper\u00f3 del crash"},
    {"chengyu": "铜墙铁壁", "pinyin": "t\u00f3ng qi\u00e1ng ti\u01eb bi", "significado": "muro de cobre y barrera de hierro", "dominio": ["defensa impenetrable"], "emocion": ["seguridad"], "ejemplo": "防御如铜墙铁壁 — defensa inquebrantable"},
    {"chengyu": "名正言顺", "pinyin": "m\u00edng zh\u00e8ng y\u00e1n sh\u00f9n", "significado": "nombre correcto, palabras fluidas", "dominio": ["legitimidad", "autoridad"], "emocion": ["confianza"], "ejemplo": "名正言顺地推行改革 — implementar reformas con autoridad"},
    {"chengyu": "震古烁今", "pinyin": "zh\u00e8n g\u01d4 shu\u00f2 j\u012bn", "significado": "conmover la antig\u00fcedad y brillar hoy", "dominio": ["grandeza", "logro"], "emocion": ["admiraci\u00f3n"], "ejemplo": "震古烁今的成就 — logros que trascienden el tiempo"},
    {"chengyu": "顺其自然", "pinyin": "sh\u00f9n q\u00ed q\u00ed r\u00e1n", "significado": "seguir su curso natural", "dominio": ["fluidez", "aceptaci\u00f3n"], "emocion": ["calma", "aceptaci\u00f3n"], "ejemplo": "问题顺其自然地解决 — los problemas se resuelven solos"},
    {"chengyu": "逆水行舟", "pinyin": "n\u00ec shu\u01d2 x\u00edng zh\u014du", "significado": "navegar contra la corriente", "dominio": ["esfuerzo constante", "perseverancia"], "emocion": ["determinaci\u00f3n"], "ejemplo": "学习如逆水行舟 — aprender es remar contra corriente"},
    {"chengyu": "未雨绸缪", "pinyin": "w\u00e8i y\u01d4 ch\u00f3u m\u00f3u", "significado": "reparar el techo antes de que llueva", "dominio": ["prevenci\u00f3n", "preparaci\u00f3n"], "emocion": ["prudencia"], "ejemplo": "在灾难前未雨绸缪 — prepararse antes del desastre"},
    {"chengyu": "画龙点睛", "pinyin": "hu\u00e0 l\u00f3ng di\u0101n j\u012bng", "significado": "pintar el drag\u00f3n y a\u00f1adir el punto", "dominio": ["toque final", "completar algo"], "emocion": ["satisfacci\u00f3n"], "ejemplo": "测试是代码的画龙点睛 — los tests son el toque final"},
    {"chengyu": "对牛弹琴", "pinyin": "du\u00ec ni\u00fa t\u00e1n q\u00edn", "significado": "tocar el la\u00fad para un buey", "dominio": ["comunicaci\u00f3n imposible", "incomprensi\u00f3n"], "emocion": ["frustraci\u00f3n"], "ejemplo": "向机器解释感情是对牛弹琴 — explicar emociones a una m\u00e1quina"},
    {"chengyu": "举一反三", "pinyin": "j\u01d4 y\u012b f\u01cen s\u0101n", "significado": "de un ejemplo, inferir tres", "dominio": ["aprendizaje", "deducci\u00f3n"], "emocion": ["curiosidad"], "ejemplo": "好程序员能举一反三 — buen programador deduce de ejemplos"},
    {"chengyu": "刻舟求剑", "pinyin": "k\u00e8 zh\u014du qi\u00fa ji\u00e0n", "significado": "marcar el barco para buscar la espada", "dominio": ["rigidez mental", "no adaptarse"], "emocion": ["frustraci\u00f3n"], "ejemplo": "用 soluciones viejas es刻舟求剑 — aferrarse a soluciones anticuadas"},
    {"chengyu": "塞翁失马", "pinyin": "s\u0101i w\u0113ng sh\u012b m\u01d4", "significado": "el viejo de la frontera perdi\u00f3 su caballo", "dominio": ["fortuna en la adversidad"], "emocion": ["esperanza"], "ejemplo": "塞翁失马，焉知非福 — la p\u00e9rdida puede ser ganancia"},
    {"chengyu": "卧薪尝胆", "pinyin": "w\u00f2 x\u012bn ch\u00e1ng d\u01cen", "significado": "dormir en lea\u00f1as y probar hiel", "dominio": ["sufrimiento por un prop\u00f3sito"], "emocion": ["determinaci\u00f3n"], "ejemplo": "卧薪尝胆，最终成功 — tras el sufrimiento, el \u00e9xito"},
    {"chengyu": "精卫填海", "pinyin": "j\u012bng w\u00e8i ti\u00e1n h\u01d2i", "significado": "Jingwei llena el mar", "dominio": ["perseverancia imposible", "constancia"], "emocion": ["determinaci\u00f3n"], "ejemplo": "像精卫填海一样坚持 — persistir aun cuando parece imposible"},
]
