      - name: Install frontend deps
        run: |
          cd tauri-frontend
          npm install
          npm install --save-dev @types/react@18.2.43 @types/react-dom@18.2.17

      - name: Build frontend
        run: |
          cd tauri-frontend
          ls node_modules/@types/react/index.d.ts
          npm run build
          
